# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tushuguanli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='AuthorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tushuguanli.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=100),
        ),
    ]
